version: '3.0'

networks:
  network-zabbix:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql
    image: mysql
    networks:
      network-zabbix:
    ports:
      - '3306:3306'
    volumes:
      - './zabbix/mysql:/var/lib/data'
    environment:
      - MYSQL_ROOT_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix

  zabbix-server:
    build:
      context: ./zabbix-server
      dockerfile: Dockerfile
    container_name: zabbix-server
    image: zabbix-server
    networks:
      network-zabbix:
    links:
      - mysql
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
      - './zabbix/zabbix-server:/var/lib/zabbix'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
    depends_on:
      - mysql

  zabbix-frontend:
    build:
      context: ./zabbix-frontend
      dockerfile: Dockerfile
    container_name: zabbix-frontend
    image: zabbix-frontend
    networks:
      network-zabbix:
    links:
      - mysql
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - './zabbix/zabbix-frontend:/var/lib/zabbix'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - PHP_TZ=America/Fortaleza
    depends_on:
      - mysql
  zabbix-agent:
    build:
      context: ./zabbix-agent
      dockerfile: Dockerfile
    container_name: zabbix-agent
    image: zabbix-agent
    user: root
    networks:
      network-zabbix:
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=172.19.0.3
